# _config.yml
title: [IT MANAGER COMPANY]
description: [Diseño, Planificación, Implementación y Mantenimiento de Soluciones de TI]

call2action: [Si necesitas asistencia técnica o cotización, escríbenos.]
email: [marco@itmanagercompany.com.ve]
country: [Venezuela]

sitestate: [Estado del sitio: Mantenimiento controlado / operación mínima]

url: https://itmanagercompany.com.ve

remote_theme: pages-themes/hacker@v0.2.0
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
 Opcionales del tema
show_downloads: false
google_analytics:

